### ISSUE TITLE
Vagrant up fails

### ISSUE THREAD

**Issue by mburgess00** [rickfarmer/android-vm#11] opened 2015-06-08 18:29 UTC
$ vagrant up
Bringing machine 'default' up with 'virtualbox' provider...
There are errors in the configuration of this machine. Please fix
the following errors and try again:

vm:
* The following settings don't exist: host_name

**Comment by rickfarmer** [comment] 2016-08-14 22:44
Unable to reproduce.  Closing.

**Closed by rickfarmer** 2016-08-14 22:44 UTC
